# Generated by Django 5.0.7 on 2025-08-29 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=10)),
                ('row_id', models.IntegerField()),
                ('row_details', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_dd2bca_idx'), models.Index(fields=['city'], name='dashboard_t_city_7f75f6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table10',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_3f7be4_idx'), models.Index(fields=['city'], name='dashboard_t_city_ef381a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_314034_idx'), models.Index(fields=['city'], name='dashboard_t_city_12ec2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table3',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_acd019_idx'), models.Index(fields=['city'], name='dashboard_t_city_8681a7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table4',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_5f1276_idx'), models.Index(fields=['city'], name='dashboard_t_city_70af8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table5',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_f8df30_idx'), models.Index(fields=['city'], name='dashboard_t_city_383973_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table6',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_b98401_idx'), models.Index(fields=['city'], name='dashboard_t_city_5b9473_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table7',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_7824ec_idx'), models.Index(fields=['city'], name='dashboard_t_city_2fe6eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table8',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_d4fa6e_idx'), models.Index(fields=['city'], name='dashboard_t_city_bb2593_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table9',
            fields=[
                ('unique_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['name'], name='dashboard_t_name_d53037_idx'), models.Index(fields=['city'], name='dashboard_t_city_f01e94_idx')],
            },
        ),
    ]
