# Generated by Django 4.2.7 on 2025-09-09 21:33

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_extend_table6_and_certificates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artistapplicationcertificate",
            name="file",
            field=models.FileField(
                upload_to="artist_certificates/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg", "webp"]
                    ),
                    apps.dashboard.models.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="artistapplicationcertificate",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
