# Generated by Django 4.2.7 on 2025-09-12 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0006_alter_table6_artist_application_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=32, unique=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=128)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "dashboard_client",
            },
        ),
        migrations.CreateModel(
            name="ClientLog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "CREATE"),
                            ("UPDATE", "UPDATE"),
                            ("DELETE", "DELETE"),
                            ("LOGIN", "LOGIN"),
                            ("LOGOUT", "LOGOUT"),
                            ("PASSWORD_RESET", "PASSWORD_RESET"),
                            ("BOOKING", "BOOKING"),
                        ],
                        max_length=20,
                    ),
                ),
                ("details", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="dashboard.client",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="client_logs_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dashboard_client_log",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["phone"], name="dashboard_c_phone_c725c1_idx"),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["email"], name="dashboard_c_email_0457a5_idx"),
        ),
        migrations.AddField(
            model_name="table10",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="dashboard.client",
            ),
        ),
        migrations.AddField(
            model_name="table9",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="dashboard.client",
            ),
        ),
        migrations.AddIndex(
            model_name="clientlog",
            index=models.Index(fields=["action"], name="dashboard_c_action_c01c86_idx"),
        ),
        migrations.AddIndex(
            model_name="clientlog",
            index=models.Index(
                fields=["timestamp"], name="dashboard_c_timesta_f5df1c_idx"
            ),
        ),
    ]
