# Generated by Django 4.2.7 on 2025-09-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0007_client_clientlog_client_dashboard_c_phone_c725c1_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="active_session_key",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
