# Generated by Django 4.2.7 on 2025-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_client_active_session_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="allow_reapply",
            field=models.BooleanField(default=False),
        ),
    ]
