# Generated by Django 4.2.7 on 2025-09-19 11:40

import apps.dashboard.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_client_allow_reapply"),
    ]

    operations = [
        migrations.AddField(
            model_name="artistapplicationcertificate",
            name="category",
            field=models.CharField(
                choices=[
                    ("certificate", "Certificate"),
                    ("supporting_picture", "Supporting Picture"),
                    ("profile_picture", "Profile Picture"),
                ],
                default="certificate",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="artistapplicationcertificate",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="artistapplicationcertificate",
            name="external_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="artistapplicationcertificate",
            name="uploaded_by_client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.client",
            ),
        ),
        migrations.AddField(
            model_name="table6",
            name="additional_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="beauty_studio_location",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="artist_applications",
                to="dashboard.client",
            ),
        ),
        migrations.AddField(
            model_name="table6",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("other", "Other"),
                    ("prefer_not_to_say", "Prefer not to say"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="table6",
            name="instagram_url",
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="instagram_username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="table6",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="artist_profiles/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "webp"]
                    ),
                    apps.dashboard.models.validate_file_size,
                ],
            ),
        ),
        migrations.AddField(
            model_name="table6",
            name="reapply_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="specialization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="supporting_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="table6",
            name="verified_badge",
            field=models.BooleanField(default=False),
        ),
    ]
