# Generated by Django 4.2.7 on 2025-09-09 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_alter_artistapplicationcertificate_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table6",
            name="artist_application_id",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, unique=True
            ),
        ),
    ]
