# Generated by Django 4.2.7 on 2025-09-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_adminprofile"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="superadmin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_super_admin", True)),
                fields=("is_super_admin",),
                name="unique_true_superadmin",
            ),
        ),
    ]
